# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a90f97d59328f94a557b3fc44698c85f347947daef08732fad4fcb823b012394b9363f63ad147e48aad377bf44c4075221b995f8d09d78ad9d117aa9660fd27

test:
  secret_key_base: b6115d229e388ba910f6f6b2195b8d3471dbbdd41703d77c3cadeb81f3350f12dc0d9b719df9818e37c59d4f7fc4ce99fc0c481ad53aca4d079ed79657f96dc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
